change-id = 144675

[build]
build-stage = 2
docs = false
compiler-docs = false
submodules = false

[rust]
channel = "nightly"
lld = true

[llvm]
download-ci-llvm = false
optimize = true
assertions = true
ninja = true
targets = "AArch64;X86"
experimental-targets = "CDM"
link-jobs = 2
link-shared = false
version-suffix = "-cdm-rust"

[target.x86_64-unknown-linux-gnu]
cc = "clang"
cxx = "clang++"
llvm-has-rust-patches = false

[target.aarch64-apple-darwin]
cc = "clang"
cxx = "clang++"
llvm-has-rust-patches = false

[dist]
compression-profile = "best"
compression-formats = ["gz"]
src-tarball = false
