name: '[CDM] Build'

on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-26]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Build Rust
        run: |
          ./x dist --ci true --config ./cdm.dist.toml
      - name: Upload rustc
        if: inputs.upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./build/dist/rustc-nightly-*.tar.gz
      - name: Upload rust-std
        if: inputs.upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./build/dist/rust-std-nightly-*.tar.gz
      - name: Upload rust-src
        if: inputs.upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./build/dist/rust-src-nightly.tar.gz
